In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
iris = datasets.load_iris()

In [3]:
X = iris.data

In [4]:
y = iris.target

In [5]:
X.shape

(150, 4)

In [9]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### train test split

In [10]:
# 不能顺序选择前xx个数据
# 1.现结合为150*5 再拆分
# 2.乱序处理index
shuffle_indexes = np.random.permutation(len(X))

In [11]:
shuffle_indexes

array([ 67, 137,  63,  45,  73,  95,  52,  29,  93,   1,  18, 102, 135,
        92,  61, 145,  74,  68, 142,  33,  71,  90,  47, 103,   8,  42,
        70, 112,  41,  50,  91,  80, 114, 105, 120,  32,  27, 149,  12,
       148,  60,  96,  25, 141, 104,  35, 106,  26, 147, 140,  38,  75,
        14, 111, 117,  89,  55, 132,  46,  39,   6,  85,  62,  66, 127,
        58,  11, 143,   5,   0, 136, 108, 138,  48, 101, 133, 130,  88,
        49,  17,  56,  23,  94,  13, 124, 115,  86,  44, 121,   9,  82,
       129, 113,  53,   3,   4,  21,  72,  24, 100,  87, 122,  15,  37,
        54,  20,  34,  81, 109,  51,  64,  78, 123,  30,  98, 110,  28,
        83, 139,  43, 126, 146,  19,  97, 144, 134, 116,  36,   2, 107,
       118,   7,  22,  76,  59,  77,  31, 131,  99,  10,  79,  16,  40,
        69,  84,  57, 119, 125, 128,  65])

In [12]:
test_ratio = 0.2

In [13]:
test_size = int(len(X) * test_ratio)

In [14]:
test_size

30

In [15]:
test_indexes = shuffle_indexes[:test_size]
train_indexes = shuffle_indexes[test_size:]
train_indexes

array([ 91,  80, 114, 105, 120,  32,  27, 149,  12, 148,  60,  96,  25,
       141, 104,  35, 106,  26, 147, 140,  38,  75,  14, 111, 117,  89,
        55, 132,  46,  39,   6,  85,  62,  66, 127,  58,  11, 143,   5,
         0, 136, 108, 138,  48, 101, 133, 130,  88,  49,  17,  56,  23,
        94,  13, 124, 115,  86,  44, 121,   9,  82, 129, 113,  53,   3,
         4,  21,  72,  24, 100,  87, 122,  15,  37,  54,  20,  34,  81,
       109,  51,  64,  78, 123,  30,  98, 110,  28,  83, 139,  43, 126,
       146,  19,  97, 144, 134, 116,  36,   2, 107, 118,   7,  22,  76,
        59,  77,  31, 131,  99,  10,  79,  16,  40,  69,  84,  57, 119,
       125, 128,  65])

In [16]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [17]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


### 使用我们自己的算法

In [18]:
from MLimooc.model_selection import train_test_split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [20]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [21]:
from MLimooc.kNN import KNNClassifier

In [22]:
my_knn_clf = KNNClassifier(k=3)

In [23]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [24]:
y_predict = my_knn_clf.predict(X_test)

In [25]:
y_predict

array([0, 1, 0, 1, 2, 2, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1,
       0, 0, 1, 0, 2, 0, 2, 2])

In [26]:
y_test

array([0, 1, 0, 1, 1, 2, 2, 2, 1, 2, 2, 1, 1, 0, 2, 0, 0, 1, 2, 1, 1, 1,
       0, 0, 1, 0, 2, 0, 2, 2])

### 相加, 如果结果相同

In [27]:
sum(y_predict == y_test)

29

In [28]:
accuracy = sum(y_predict == y_test)/len(y_test)

In [29]:
accuracy

0.9666666666666667

## sklearn中的train_test_split

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 2)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [32]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [33]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
sk_kNN_clf = KNeighborsClassifier(n_neighbors=6)

In [36]:
sk_kNN_clf.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [37]:
y_sk_predict = sk_kNN_clf.predict(X_test)

In [38]:
y_sk_predict

array([2, 2, 1, 1, 0, 0, 0, 0, 2, 2, 0, 2, 2, 1, 1, 1, 0, 1, 1, 1, 0, 2,
       2, 1, 1, 0, 2, 2, 0, 2])

In [39]:
y_test

array([1, 2, 1, 1, 0, 0, 0, 0, 2, 2, 0, 1, 2, 1, 1, 1, 0, 1, 1, 1, 0, 2,
       2, 1, 1, 0, 2, 2, 0, 2])

In [40]:
accuracy = sum(y_sk_predict == y_test)/len(y_test)

In [41]:
accuracy

0.9333333333333333